class Data_info:
    def __init__(self):
        self.isCommunication_stop = '0003\x00'
        self.data_info = {
            '0000': '',
            '0001': 'Communication start',
            '0002': 'Communication start acknowledge',
            '0003': 'Communication stop',
            '0004': 'Command error',
            '0005': 'Command accepted',
            '0010': 'Application ID upload request',
            '0011': 'Application ID upload reply',
            '0012': 'Application data upload request',
            '0013': 'Application data upload reply',
            '0014': 'Application selected subscribe',
            '0015': 'Application selected',
            '0016': 'Application selected acknowledge',
            '0017': 'Application selected unsubscribe',
            '0018': 'Select Application',
            '0019': 'Set Application batch size',
            '0020': 'Reset Application batch counter',
            '0021': 'Lock at batch done subscribe',
            '0022': 'Lock at batch done upload',
            '0023': 'Lock at batch done upload acknowledge',
            '0024': 'Lock at batch done unsubscribe',
            '0030': 'Linking Group ID upload request',
            '0031': 'Linking Group ID upload reply',
            '0032': 'Linking Group data upload request',
            '0033': 'Linking Group data upload reply',
            '0034': 'Linking Group info subscribe',
            '0035': 'Linking Group info',
            '0036': 'Linking Group info acknowledge',
            '0037': 'Linking Group info unsubscribe',
            '0038': 'Select Linking Group',
            '0039': 'Linking Group restart',
            '0040': 'Tool data upload request',
            '0041': 'Tool data upload reply',
            '0042': 'Disable tool',
            '0043': 'Enable tool',
            '0050': 'Vehicle Id Number download request',
            '0051': 'Vehicle Id Number upload subscribe',
            '0052': 'Vehicle Id Number upload',
            '0053': 'Vehicle Id Number upload acknowledge',
            '0054': 'Vehicle Id Number upload unsubscribe',
            '0060': 'Last tightening result data subscribe',
            '0061': 'Last tightening result data upload',
            '0062': 'Last tightening result data acknowledge',
            '0063': 'Last tightening result data unsubscribe',
            '0064': 'Old tightening result upload request',
            '0065': 'Old tightening result reply',
            '0070': 'Alarm subscribe',
            '0071': 'Alarm Upload',
            '0072': 'Alarm Upload acknowledge',
            '0073': 'Alarm Unsubscribe',
            '0074': 'Alarm Acknowledged on torque controller',
            '0075': 'Alarm Acknowledged acknowledge',
            '0076': 'Alarm Status',
            '0077': 'Alarm Status acknowledge',
            '0080': 'Time upload request',
            '0081': 'Time upload reply',
            '0082': 'Set Time in the Torque Controller',
            '0090': 'Multi-spindle status subscribe',
            '0091': 'Multi-spindle status',
            '0092': 'Multi-spindle status acknowledge',
            '0093': 'Multi-spindle status unsubscribe',
            '0100': 'Multi-spindle results subscribe',
            '0101': 'Multi-spindle results',
            '0102': 'Multi-spindle results acknowledge',
            '0103': 'Multi-spindle results unsubscribe',
            '0111': 'Display user text on graph',
            '0113': 'Flash green LED on Tool',
            '0127': 'Abort Linking Group',
            '0128': 'Linking Group batch increment',
            '0129': 'Linking Group batch decrement',
            '0150': 'Identifier download request',
            '0200': 'Set external controlled relays',
            '0210': 'Status external monitored inputs subscribe',
            '0211': 'Status external monitored inputs',
            '0212': 'Status external monitored inputs acknowledge',
            '0213': 'Status external monitored inputs unsubscribe',
            '0214': 'IO device status request',
            '0215': 'IO device status reply',
            '0216': 'Relay function subscribe',
            '0217': 'Relay function',
            '0218': 'Relay function acknowledge',
            '0219': 'Relay function unsubscribe',
            '0220': 'Digital input function subscribe',
            '0221': 'Digital input function',
            '0222': 'Digital input function acknowledge',
            '0223': 'Digital input function unsubscribe',
            '0250': 'Selector Socket info subscribe',
            '0251': 'Selector Socket info',
            '0252': 'Selector Socket info acknowledge',
            '0253': 'Selector Socket info unsubscribe',
            '0254': 'Selector Control green light',
            '0410': 'AutoDisable settings request',
            '0411': 'AutoDisable settings reply',
            '9999': 'Keep alive message',
        }

    def toMsg(self, key):
        txt_msg = self.data_info[key]
        return txt_msg