    # open = OpenProtocol(HOST, PORT)
    # cmd = cmd_OpenProtocol()
    # open.send_msg(cmd.Communication_stop())
    # time.sleep(0.1)
    # open.send_msg(cmd.Communication_start())
    # time.sleep(0.1)
    # open.send_msg(cmd.Disable_tool())
    # time.sleep(0.1)
    # open.send_msg(cmd.Enable_tool())
    # time.sleep(0.1)
    # open.send_msg(cmd.Last_tightening_result_data_subscribe())
    # time.sleep(0.1)
    # while True:
    #     open.send_msg(cmd.Communication_start())
    #     time.sleep(0.1)
    #     open.send_msg(cmd.Enable_tool())